# Generated by Django 5.0.2 on 2024-02-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deletetime',
            field=models.DateTimeField(blank=True),
        ),
    ]
