# Generated by Django 5.0.2 on 2024-02-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_deletetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deletetime',
            field=models.DateTimeField(null=True),
        ),
    ]
